cacheDir: /home/codespace/.lumineer/cache
gitCredentialsPath: "/home/codespace/ado-auth-helper"
login:
  commands:
    azure:
      name: az
      args:
        - login
        - --allow-no-subscriptions
  enabled: true
userEmail: pjindal@slb.com